language: php
sudo: required
env:
    - RUN=vendor/bin/phpunit

script: ${RUN}

php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3
    - hhvm
    - nightly

before_script:
    - "composer selfupdate"
    - "composer --version"
    - "composer install --prefer-dist --verbose"
